In [5]:
%pip install numpy
import numpy as np

# ============================================================================
# 5. 實戰：用線性代數模擬一個完整的前向傳播
# ============================================================================
print("\n" + "=" * 60)
print("5. 實戰：用純 NumPy 模擬神經網路前向傳播")
print("=" * 60)

# 模擬一個 3 層神經網路：
#   輸入：4 個特徵
#   隱藏層 1：8 個神經元
#   隱藏層 2：6 個神經元
#   輸出：3 個類別（分類問題）

np.random.seed(42)

# 模擬一批 5 個樣本，每個有 4 個特徵
X = np.random.randn(5, 4)    # shape: (batch_size=5, features=4)

# 權重和偏差（通常隨機初始化）
W1 = np.random.randn(4, 8) * 0.01   # (4, 8)  4 輸入 → 8 輸出
b1 = np.zeros((1, 8))                # (1, 8)  每個輸出一個 bias
W2 = np.random.randn(8, 6) * 0.01   # (8, 6)  8 輸入 → 6 輸出
b2 = np.zeros((1, 6))
W3 = np.random.randn(6, 3) * 0.01   # (6, 3)  6 輸入 → 3 輸出
b3 = np.zeros((1, 3))

# 激活函數（非線性，Phase 2 會詳細講）
def relu(x):
    return np.maximum(0, x)          # 小於 0 的變成 0，其他不變

def softmax(x):
    exp_x = np.exp(x - x.max(axis=1, keepdims=True))   # 減最大值防溢出
    return exp_x / exp_x.sum(axis=1, keepdims=True)

# 前向傳播
print("各層形狀變化：")
print(f"  輸入 X:  {X.shape}")            # (5, 4)

z1 = X @ W1 + b1                          # 線性變換（broadcasting: b1 廣播到每個樣本）
a1 = relu(z1)                             # 非線性激活
print(f"  第 1 層: {X.shape} @ {W1.shape} + {b1.shape} → {a1.shape}")

z2 = a1 @ W2 + b2
a2 = relu(z2)
print(f"  第 2 層: {a1.shape} @ {W2.shape} + {b2.shape} → {a2.shape}")

z3 = a2 @ W3 + b3
output = softmax(z3)                       # 最後一層用 Softmax 得到機率
print(f"  第 3 層: {a2.shape} @ {W3.shape} + {b3.shape} → {output.shape}")

print(f"\n輸出（每個樣本對 3 個類別的機率）：")
print(output.round(4))
print(f"每列總和（應該都是 1）: {output.sum(axis=1).round(4)}")

# 預測結果
predictions = output.argmax(axis=1)
print(f"預測類別: {predictions}")


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 1.1 MB/s  0:00:14m0:00:0100:01m
Note: you may need to restart the kernel to use updated packages.

5. 實戰：用純 NumPy 模擬神經網路前向傳播
各層形狀變化：
  輸入 X:  (5, 4)
  第 1 層: (5, 4) @ (4, 8) + (1, 8) → (5, 8)
  第 2 層: (5, 8) @ (8, 6) + (1, 6) → (5, 6)
  第 3 層: (5, 6) @ (6, 3) + (1, 3) → (5, 3)

輸出（每個樣本對 3 個類別的機率）：
[[0.3333 0.3333 0.3333]
 [0.3333 0.3333 0.3333]
 [0.3333 0.3333 0.3333]
 [0.3333 0.3333 0.3333]
 [0.3333 0.3333 0.3333]]
每列總和（應該都是 1）: [1. 1. 1. 1. 1.]
預測類別: [1 1 2 2 2]
